# Generated by Django 5.0.3 on 2024-05-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "short_description",
                    models.CharField(max_length=30, verbose_name="Краткое описание"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "small_preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Малое превью"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Превью"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
