# Generated by Django 5.0.3 on 2024-05-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "__first__"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info_about_service",
                    models.CharField(max_length=50, verbose_name="Описание"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("PRESCHOOLER", "Дошкольники"),
                            ("SCHOLAR", "Школьники"),
                            ("STUDENT", "Студенты"),
                            ("OTHER", "Другие"),
                        ],
                        max_length=15,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subjects.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="tutors.tutor",
                        verbose_name="Репетитор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
