# Generated by Django 5.0.3 on 2024-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="info_about_service",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
