# Generated by Django 5.0.3 on 2024-05-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_info_about_service"),
        ("students", "0003_alter_student_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Дата и время старта"),
                ),
                (
                    "duration",
                    models.IntegerField(verbose_name="Продолжительность (минуты)"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="services.service",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот услуги",
                "verbose_name_plural": "Слоты услуг",
                "ordering": ["start_time"],
            },
        ),
    ]
