# Generated by Django 5.0.3 on 2024-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_serviceslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
