# Generated by Django 5.0.3 on 2024-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_service_is_approved_service_is_done"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_done",
        ),
        migrations.AddField(
            model_name="serviceslot",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceslot",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
