# Generated by Django 5.0.3 on 2024-05-26 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=20, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                (
                    "email",
                    models.CharField(max_length=30, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "education",
                    models.TextField(max_length=255, verbose_name="Образование"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Репетитор",
                "verbose_name_plural": "Репетиторы",
            },
        ),
    ]
