# Generated by Django 5.0.3 on 2024-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0002_alter_tutor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="tutors/photos"),
        ),
    ]
