# Generated by Django 5.0.3 on 2024-03-18 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0002_new_delete_news_alter_administrator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='tutor_id',
        ),
        migrations.RemoveField(
            model_name='registragtion_for_service',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='registragtion_for_service',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='registragtion_for_service',
            name='tutor_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tutor_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AddField(
            model_name='registragtion_for_service',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.service'),
        ),
        migrations.AddField(
            model_name='registragtion_for_service',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student'),
        ),
        migrations.AddField(
            model_name='registragtion_for_service',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AddField(
            model_name='service',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='registragtion_for_service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
