# Generated by Django 5.0.3 on 2024-03-18 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0003_remove_administrator_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AlterField(
            model_name='registragtion_for_service',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.service'),
        ),
        migrations.AlterField(
            model_name='registragtion_for_service',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student'),
        ),
        migrations.AlterField(
            model_name='registragtion_for_service',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user'),
        ),
    ]
