# Generated by Django 5.0.3 on 2024-03-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0004_alter_administrator_user_alter_homework_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.RenameModel(
            old_name='Registragtion_for_service',
            new_name='Registration_for_service',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='services',
        ),
        migrations.AlterField(
            model_name='service',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.subject'),
        ),
    ]
