# Generated by Django 5.0.3 on 2024-03-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0005_rename_new_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tutor', to='tutoring_center.tutor'),
        ),
    ]
