# Generated by Django 5.0.3 on 2024-03-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0008_alter_service_tutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Репетитор', 'verbose_name_plural': 'Репетиторы'},
        ),
    ]
