# Generated by Django 5.0.3 on 2024-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0009_alter_tutor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='level',
            field=models.CharField(choices=[('preschooler', 'preschooler'), ('scholar', 'scholar'), ('student', 'student'), ('other', 'other')], max_length=15),
        ),
    ]
