# Generated by Django 5.0.3 on 2024-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0011_alter_service_info_about_service_alter_service_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='service',
            name='level',
            field=models.CharField(choices=[('PRESCHOOLER', 'Дошкольники'), ('SCHOLAR', 'Школьники'), ('STUDENT', 'Студенты'), ('OTHER', 'Другие')], max_length=15, verbose_name='Уровень'),
        ),
    ]
