# Generated by Django 5.0.3 on 2024-03-18 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0012_alter_service_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parents_fio',
        ),
        migrations.AddField(
            model_name='file',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_fio',
            field=models.CharField(max_length=100, null=True, verbose_name='ФИО родителя'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер телефона родителя'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='news/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(max_length=30, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='theme',
            field=models.CharField(max_length=30, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor', verbose_name='Репетитор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=30, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_preview',
            field=models.ImageField(upload_to='', verbose_name='Малое превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('PRESCHOOLER', 'Дошкольники'), ('SCHOLAR', 'Школьники'), ('STUDENT', 'Студенты'), ('OTHER', 'Другие')], max_length=15, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='education',
            field=models.TextField(max_length=255, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='tutoring_center.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='RegistrationForService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца')),
                ('theme_of_lesson', models.CharField(max_length=30, verbose_name='Тема урока')),
                ('additional_info', models.CharField(max_length=30, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('FREE', 'Свободно'), ('BUSY', 'Занято'), ('CONFIRMED', 'Подтверждено'), ('COMPLETED', 'Завершено')], max_length=15, verbose_name='Статус')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.service', verbose_name='Услуга')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.student', verbose_name='Ученик')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_center.tutor', verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.DeleteModel(
            name='Registration_for_service',
        ),
    ]
