# Generated by Django 5.0.3 on 2024-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0013_alter_administrator_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_preview',
            field=models.ImageField(null=True, upload_to='', verbose_name='Малое превью'),
        ),
    ]
