# Generated by Django 5.0.3 on 2024-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_center', '0014_alter_news_description_alter_news_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Малое превью'),
        ),
    ]
